---
- hosts: all
  become: yes

  pre_tasks:

    - include_tasks: configure_hostnames.yml

    - name: Update apt cache
      apt: update_cache=yes cache_valid_time=3600  # 1 hr

    - name: Check if this is the first run of the play (absence of ~/hadoop)
      stat:
        path: "/home/{{ ansible_user }}/hadoop"
      register: hadoop_home

    - name: Perform a comprehensive upgrade on first run
      # we assume absence of ~/hadoop indicates this is first run
      apt: upgrade=dist
      when: hadoop_home.stat.isdir is not defined or not hadoop_home.stat.isdir
      notify: reboot server

    - name: Perform safe upgrade
      # Safe upgrade on subsequent runs to limit any data loss risks
      apt: upgrade=safe
      when: hadoop_home.stat.isdir is defined and hadoop_home.stat.isdir

  tasks:

    - name: Signal from guest vm
      debug:
        msg: "Hello from {{ inventory_hostname }}"

    # setup master ssh access
    - name: Ensure master hadoop user has an SSH key
      community.crypto.openssh_keypair:
        path: /home/{{ ansible_user }}/.ssh/id_rsa
      become: no
      when: inventory_hostname == "master"

  handlers:
    - name: reboot server
      reboot: msg="Rebooting host"

    - name: restart networking
      service: name=networking state=restarted
