---
- name: Rename hostname in /etc/hostname
  hostname:
    name: "{{ inventory_hostname }}"
  notify: reboot server

# todo: fix issue with duplicate hostname entries
- name: Set cluster entries in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^.*\b{{ item }}\b.*'
    line: '{{ hostvars[item]["ansible_host"] }} {{ item }}'
    state: present
  loop: "{{ groups['all'] }}"  # loop by hostname
  notify: reboot server
