---
- name: Setup hadoop environment variables
  template:
    src: templates/etc_profile_hadoop.sh.j2
    dest: /etc/profile.d/hadoop.sh

- name: Setup JAVA_HOME in hadoop-env.sh
  lineinfile:
    dest: "{{ hadoop_home }}/etc/hadoop/hadoop-env.sh"
    regexp: "^export JAVA_HOME"
    line: "export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64"
    state: present

- name: Configure hadoop site
  template:
    src: templates/hadoop-site-config.xml.j2
    dest: "{{ hadoop_home }}/etc/hadoop/{{ item.key }}.xml"
  vars:
    config_dict: "{{ item.value }}"
  loop: "{{ hadoop_site_configuration | dict2items }}"

- name: Specify workers
  template:
    src: templates/cluster_workers.j2
    dest: "{{ hadoop_home }}/etc/hadoop/workers"

- name: Ensure logs directory is writeable by hadoop user
  file:
    path: "{{ hadoop_home }}/logs"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
